# Site settings
title: Noah Liebman
description: > # this means to ignore newlines until "baseurl:"
  Noah Liebman studies computer science and communication studies at Northwestern University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://noahliebman.net" # the base hostname & protocol for your site
assets: //assets.noahliebman.net
permalink: /:year/:month/:title/
paginate: 10
debug: false

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - 
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
